# Global options

# Address to listen on
listen_address: "0.0.0.0"
# Ports to listen on by default. Set to 0 to disable
http_port: 8080
#https_port: 8443
https_port: 0
# Redirect HTTP requests to HTTPS?
https_redirect: true

ldap:
  host: "ldap.example.com"
  port: 636
  ssl: true
  starttls: false
  base: "dc=example,dc=com"
  bind_dn: ""
  bind_pw: ""
  # Override the default user filter of "(uid=%s)"
  #user_filter: ""
  # Override the default group filter of "(memberUid=%s)"
  #group_filter: ""

# Cert must contain the full chain
tls:
  cert: cert.crt
  key: key.key

# List of virtual hosts
hosts:
  # Users must be in one of allow_groups or must be one of the users in allow_users
  # deny_users and deny_groups overrides allow_groups and allow_users
  - hostnames:
      - nedlinux:8080
      - test1.mydomain.xyz
      - test1.otherdomain.com
    upstream: "http://chef2"
    allow_groups:
      - group1
      - group2
    allow_users:
      - user1
      - user2
    deny_groups:
      - denied_group1
    deny_users:
      - denied_user1

  # Example allowing all users who authenticate successfully
  - hostnames:
      - test2.mydomain.xyz
    upstream: "http://localhost:1234"
    # Allow all users without checking username or group membership
    allow_all: true
