# Global options

# Address to listen on
listen_address: "0.0.0.0"
# Ports to listen on by default. Set to 0 to disable
http_port: 8080
#https_port: 8443
https_port: 0
# Redirect HTTP requests to HTTPS?
https_redirect: true

# Internal users. This list will be consulted before LDAP
internal_users:
  - username: user1
    password: password1
    groups:
      - group1
      - group2
  - username: user2
    password: password2
    groups:
      - group2
      - group3

# LDAP servers will be attempted in order
ldap_servers:
  - host: "ldap.example.com"
    port: 636
    ssl: true
    starttls: false
    # How many times to attempt LDAP operations before giving up
    call_attempts: 5
    base: "dc=example,dc=com"
    bind_dn: "cn=admin,dc=example,dc=com"
    bind_pw: "admin_passwd"
    # Override the default user filter of "(uid=%s)"
    #user_filter: ""
    # Override the default group filter of "(memberUid=%s)"
    # For JumpCloud use "(member=uid=%s,BASE_DN)", replacing BASE_DN with your base DN
    #group_filter: ""
    # How long in seconds to cache user credentials and groups
    cache_seconds: 60

# Cert must contain the full chain
tls:
  cert: cert.crt
  key: key.key

# List of virtual hosts
hosts:
  # Users must be in one of allow_groups or must be one of the users in allow_users
  # deny_users and deny_groups overrides allow_groups and allow_users
  - hostnames:
      - test1.mydomain.xyz
      - test1.otherdomain.com
    upstream: "http://127.0.0.1:4000"
    allow_groups:
      - group1
      - group2
    allow_users:
      - user1
      - user2
    deny_groups:
      - denied_group1
    deny_users:
      - denied_user1

  # Example allowing all users who authenticate successfully
  - hostnames:
      - test2.mydomain.xyz
    upstream: "http://localhost:1234"
    # Allow all users without checking username or group membership
    allow_all: true
