# Global options

# Address to listen on
listen_address: "0.0.0.0"
# Ports to listen on by default. Set to 0 to disable
http_port: 80
https_port: 443
# Redirect HTTP requests to HTTPS?
https_redirect: true

ldap:
  server: "ldaps://ldap.jumpcloud.com:631"
  bind_dn: ""
  bind_pw: ""

# Cert must contain the full chain
tls:
  enabled: true
  cert: cert.crt
  key: key.key

# List of virtual hosts
hosts:
  # Users must be in one of allow_groups or must be one of the users in allow_users
  # deny_users and deny_groups overrides allow_groups and allow_users
  - hostnames:
    - test1.mydomain.xyz
    - test1.otherdomain.com
    upstream: "http://localhost:4440"
    allow_groups:
      - group1
      - group2
    allow_users:
      - user1
      - user2
    deny_groups:
      - denied_group1
    deny_users:
      - denied_user1

  # No allow_users or allow_groups will allow all users who authenticate successfully
  - hostnames:
    - test2.mydomain.xyz
    upstream: "http://localhost:1234"
